### ISSUE TITLE
File level ownership matching

### ISSUE THREAD

**Issue by mohlson** [spotify/ruler#52]
### Feature description

Hi! Would it be feasible to support more granular ownership matching? 
I.e. down to the file level, such as in a GitHub CODEOWNERS file?

Maybe even accept a CODEOWNERS file as input for ownership?

### Reasoning

* Being able to deal with modules with split ownership
* Not having to maintain two separate lists of ownership

**Comment by simonschiller** [comment]
Thanks for the feature request! We actually thought about adding file-level ownership support but decided against it back in the day. The reason was that (based on our experience) mixed ownership inside one module can lead to confusion and conflicts. Our recommendation is to split the files into separate modules, which then can have different owners.

That being said, if this is a feature that would help a lot of people we are not super opposed to it. I'd say let's keep this issue open to see how many people are interested in this.

**Comment by mohlson** [comment]
We're not quite as far along the modularisation path as Spotify is, so we do still have a massive App module with lots of owners of different subparts. Although I completely agree with your analysis, from a practical perspective we would appreciate it a bunch. :D

> That being said, if this is a feature that would help a lot of people we are not super opposed to it. I'd say let's keep this issue open to see how many people are interested in this.

Sounds great!

**Comment by cckroets** [comment]
+1 to this feature request.

In my experience, I like to keep code-ownership and code-modularization completely separate. A large company could re-org three times over, creating new teams, morphing old teams, but that doesn't mean we should refactor the whole codebase. Modularize code based on need, not based on ownership.

**Comment by simonschiller** [comment]
This is now supported in the 1.2.0 release. Feel free to try it out and let us know what you think!

**Comment by mohlson** [comment]
Awesome, thank you! Will give it a spin!
