### ISSUE TITLE
No report for Dynamic feature module

### ISSUE THREAD

**Issue by doniwinata0309** [spotify/ruler#55]
### Current behavior

Cannot find any report for all dynamic feature module 

### Expected behavior

Report showing dynamic feature module size

### Steps to reproduce

Analyze project with DFM module

### Versions

1.1.0

### Anything else?

Hi, I am not sure why my DFM module not showing up on the report. It seems only showing base apk, is it expected or there some additional settings we need to add if want to analyze DFM module?

Thank you in advance

**Comment by simonschiller** [comment]
Thanks for reporting this!

This is kind of expected and by design, as dynamic feature modules are typically not packaged with the main app. Because of that we'd probably want to separate DFMs from the normal app somehow in the reports, but it's probably a good idea to also include them in the analysis.

**Comment by doniwinata0309** [comment]
yes, would be awesome if we can view DFM size as well from report. Thank you for considering it.

**Comment by simonschiller** [comment]
This should be fixed in the 1.3.0 version we just released - thanks for reporting!
